version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 3333:3333
    depends_on:
      - db
    environment:
      PG_HOST: db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ignitemanager_db
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - 5432:5432

volumes:
  postgres-data:
